Ext.define('EscuelaFutbol.model.Jugadores', {
extend: 'Ext.data.Model',
        fields: [
        {name:'codigo'},
        {name:'doc_identidad'},
        {name:'tipo_documento'},
        {name:'fecha_expedicion'},
        {name:'nombres'},
        {name:'apellidos'},
        {name:'seguridad_social'},
        {name:'fecha_nacimiento'},
        {name:'codigo_lugar_nacimiento'},
        {name:'tipo_sangre'},
        {name:'direccion'},
        {name:'barrio'},
        {name:'telefono'},
        {name:'celular'},
        {name:'email'},
        {name:'BB_PIN'},
        {name:'colegio'},
        {name:'grado'},
        {name:'codigo_suscriptor'},
        {name:'foto'},
        {name:'genero'},
        {name:'estado'},
        {name:'fecha_ingreso'},
        {name:'codigo_categoria'},
        {name :'nombre_completo'},
        {name :'observaciones'}
        ]
});